name: image_enhancement
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_spinkit: ^5.1.0
  pin_code_fields: ^7.4.0
  bot_toast: ^4.0.3
  dots_indicator: ^2.1.0
  shared_preferences: ^2.0.15
  http: ^0.13.6
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  cached_network_image: ^3.2.3
  flutter_styled_toast: ^2.1.3
  shimmer: ^3.0.0
  image_picker: ^0.8.7+5
  file_picker: ^5.2.7
  open_file: ^3.3.1
  url_launcher: ^6.1.11
  lottie: ^2.3.2
  mime: ^1.0.4
  get: ^4.6.5
  flutter_staggered_animations:
  carousel_slider: ^4.2.1
  avatar_glow:
  dio: ^5.2.1+1
  path_provider: ^2.0.15
  flutter_svg_provider: ^1.0.3
  particles_flutter:
  video_player: ^2.7.0
  intl: ^0.17.0
   
dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/videos/
    
    

